version: 2
jobs:
  xenial_testing:
    docker:
      - image: iancolwell/xenial_user:latest
    steps:
      - checkout
      - run: bash opera_install.bash

  bionic_testing:
    docker:
      - image: iancolwell/bionic_user:latest
    steps:
      - checkout
      - run: bash opera_install.bash