version: 2
jobs:
  xenial_testing:
    docker:
      - image: iancolwell/ubuntu:xenial_user
    steps:
      - checkout
      - run: bash opera_install.bash

  bionic_testing:
    docker:
      - image: iancolwell/ubuntu:bionic_user
    steps:
      - checkout
      - run: bash opera_install.bash
