version: 2
jobs:
  focal_desktop-testing:
    docker:
      - image: iancolwell/ubuntu:focal_desktop
    steps:
      - run: sudo apt-get update && sudo apt-get -y install git openssh-client
      - checkout
      - run: bash .circleci/ci_test.bash

  jammy_desktop-testing:
    docker:
      - image: iancolwell/ubuntu:jammy_desktop
    steps:
      - run: sudo apt-get update && sudo apt-get -y install git openssh-client
      - checkout
      - run: bash .circleci/ci_test.bash

workflows:
  version: 2
  ubuntu_testing:
    jobs:
      - focal_desktop-testing
      - jammy_desktop-testing
