version: 2
jobs:
  build:
    docker:
      - image: iancolwell/xenial_desktop:latest
        environment:
          CONTINUOUS_INTEGRATION: TRUE
    steps:
      - checkout
      - run: bash opera_install.bash
